import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'overview'
    },
    {
      type: 'category',
      label: 'STIX Domain Objects',
      items: [{
        type: 'autogenerated',
        dirName: 'SDO'
      }],
    },
    {
      type: 'category',
      label: 'STIX Relationship Objects',
      items: [{
        type: 'autogenerated',
        dirName: 'SRO'
      }],
    },
    {
      type: 'category',
      label: 'STIX Meta Objects',
      items: [{
        type: 'autogenerated',
        dirName: 'SMO'
      }],
    },
  ],
};

export default sidebars;
